config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :consumers
  resources :user_labels
  resources :user_artists
  resources :tracks
  resources :releases
  resources :labels
  resources :artists
  
  controller :sessions do
	get 'login'=> :new
	post 'login' => :create
	get 'logout' => :destroy
	delete 'logout' => :destroy
end

controller :pages do
	get 'profile' => :profile
end
  
  root 'pages#home'
	
  
 
 

end

app/models/label.rb
class Label < ActiveRecord::Base
	has_many:releases, dependent:  :destroy
	has_many:userLabels, dependent:  :destroy
end

app/controllers/labels_controller.rb
class LabelsController < ApplicationController
  before_action :set_label, only: [:show, :edit, :update, :destroy]
  before_filter :authorise, :except =>[:index]
  
  # GET /labels
  # GET /labels.json
  def index
    @labels = Label.all
  end

  # GET /labels/1
  # GET /labels/1.json
  def show
  end

  # GET /labels/new
  def new
    @label = Label.new
  end

  # GET /labels/1/edit
  def edit
  end

  # POST /labels
  # POST /labels.json
  def create
    @label = Label.new(label_params)

    respond_to do |format|
      if @label.save
        format.html { redirect_to @label, notice: 'Label was successfully created.' }
        format.json { render :show, status: :created, location: @label }
      else
        format.html { render :new }
        format.json { render json: @label.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /labels/1
  # PATCH/PUT /labels/1.json
  def update
    respond_to do |format|
      if @label.update(label_params)
        format.html { redirect_to @label, notice: 'Label was successfully updated.' }
        format.json { render :show, status: :ok, location: @label }
      else
        format.html { render :edit }
        format.json { render json: @label.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /labels/1
  # DELETE /labels/1.json
  def destroy
    @label.destroy
    respond_to do |format|
      format.html { redirect_to labels_url, notice: 'Label was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_label
      @label = Label.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def label_params
      params.require(:label).permit(:name, :location, :image, :owner)
    end
end

app/helpers/labels_helper.rb
module LabelsHelper
end

app/views/labels/_form.html.erb
<%= form_for(@label) do |f| %>
  <% if @label.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@label.errors.count, "error") %> prohibited this label from being saved:</h2>

      <ul>
      <% @label.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :owner %><br>
    <%= f.text_field :owner %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/labels/edit.html.erb
<h1>Editing Label</h1>

<%= render 'form' %>

<%= link_to 'Show', @label %> |
<%= link_to 'Back', labels_path %>

app/views/labels/index.html.erb
<p id="notice"><%= notice %></p>

<h2 class = "sub-header">Labels</h2>
<div class = "table-responsive">
<table class = "table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Location</th>
      <!--<th>Image</th>-->
      <th>Owner</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @labels.each do |label| %>
      <tr>
        <td><%= label.name %></td>
        <td><%= label.location %></td>
        <!--<td><%= label.image %></td>-->
        <td><%= label.owner %></td>
        <td><%= link_to 'Show', label %></td>
        <td><%= link_to 'Edit', edit_label_path(label) %></td>
        <td><%= link_to 'Destroy', label, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<br>

<%= link_to 'New Label', new_label_path %>

app/views/labels/new.html.erb
<h1>New Label</h1>

<%= render 'form' %>

<%= link_to 'Back', labels_path %>

app/views/labels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @label.name %>
</p>

<p>
  <strong>Location:</strong>
  <%= @label.location %>
</p>

<p>
  <strong>Image:</strong>
    <%= image_tag(@label.image, :alt => "", :size=>"120x100") %>
</p>

<p>
  <strong>Owner:</strong>
  <%= @label.owner %>
</p>

<strong>Releases:</strong>
<% @label.releases.each do |release| %>
	<br><%=release.name %>
<% end %>
<br>
<br>
<%= button_to 'Follow', user_labels_path(label_id: @label)%></br>
<%= link_to 'Edit', edit_label_path(@label) %> |
<%= link_to 'Back', labels_path %>