config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :consumers
  resources :user_labels
  resources :user_artists
  resources :tracks
  resources :releases
  resources :labels
  resources :artists
  
  controller :sessions do
	get 'login'=> :new
	post 'login' => :create
	get 'logout' => :destroy
	delete 'logout' => :destroy
end

controller :pages do
	get 'profile' => :profile
end
  
  root 'pages#home'
	
  
 
 

end

app/models/user_label.rb
class UserLabel < ActiveRecord::Base
	belongs_to:user
	belongs_to:label
end

app/controllers/user_labels_controller.rb
class UserLabelsController < ApplicationController
  before_action :set_user_label, only: [:show, :edit, :update, :destroy]
  before_action :authorise
  # GET /user_labels
  # GET /user_labels.json
  def index
    @user_labels = UserLabel.all
  end

  # GET /user_labels/1
  # GET /user_labels/1.json
  def show
  end

  # GET /user_labels/new
  def new
    @user_label = UserLabel.new
  end

  # GET /user_labels/1/edit
  def edit
  end

  # POST /user_labels
  # POST /user_labels.json
  def create
	@user_label = UserLabel.new
	@label = Label.find params[:label_id]
	@user_label.user_id = @current_user.id
	@user_label.label_id = @label.id
	
    respond_to do |format|
      if @user_label.save
        format.html { redirect_to @label, notice: 'User label was successfully created.' }
        format.json { render :show, status: :created, location: @user_label }
      else
        format.html { render :new }
        format.json { render json: @user_label.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_labels/1
  # PATCH/PUT /user_labels/1.json
  def update
    respond_to do |format|
      if @user_label.update(user_label_params)
        format.html { redirect_to @user_label, notice: 'User label was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_label }
      else
        format.html { render :edit }
        format.json { render json: @user_label.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_labels/1
  # DELETE /user_labels/1.json
  def destroy
    @user_label.destroy
    respond_to do |format|
      format.html { redirect_to user_labels_url, notice: 'User label was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_label
      @user_label = UserLabel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_label_params
      params.require(:user_label).permit(:user_id, :label_id)
    end
end

app/helpers/user_labels_helper.rb
module UserLabelsHelper
end

app/views/user_labels/_form.html.erb
<%= form_for(@user_label) do |f| %>
  <% if @user_label.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_label.errors.count, "error") %> prohibited this user_label from being saved:</h2>

      <ul>
      <% @user_label.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :label_id %><br>
    <%= f.number_field :label_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_labels/edit.html.erb
<h1>Editing User Label</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_label %> |
<%= link_to 'Back', user_labels_path %>

app/views/user_labels/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing User Labels</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Label</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_labels.each do |user_label| %>
      <tr>
        <td><%= user_label.user_id %></td>
        <td><%= user_label.label_id %></td>
        <td><%= link_to 'Show', user_label %></td>
        <td><%= link_to 'Edit', edit_user_label_path(user_label) %></td>
        <td><%= link_to 'Destroy', user_label, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User label', new_user_label_path %>

app/views/user_labels/new.html.erb
<h1>New User Label</h1>

<%= render 'form' %>

<%= link_to 'Back', user_labels_path %>

app/views/user_labels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @user_label.user_id %>
</p>

<p>
  <strong>Label:</strong>
  <%= @user_label.label_id %>
</p>

<%= link_to 'Edit', edit_user_label_path(@user_label) %> |
<%= link_to 'Back', user_labels_path %>