config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :consumers
  resources :user_labels
  resources :user_artists
  resources :tracks
  resources :releases
  resources :labels
  resources :artists
  
  controller :sessions do
	get 'login'=> :new
	post 'login' => :create
	get 'logout' => :destroy
	delete 'logout' => :destroy
end

controller :pages do
	get 'profile' => :profile
end
  
  root 'pages#home'
	
  
 
 

end

app/models/artist.rb
class Artist < ActiveRecord::Base
	has_many:releases, dependent:  :destroy
	has_many:userArtists, dependent:  :destroy
end

app/models/label.rb
class Label < ActiveRecord::Base
	has_many:releases, dependent:  :destroy
	has_many:userLabels, dependent:  :destroy
end

app/models/release.rb
class Release < ActiveRecord::Base
	has_many:tracks, dependent:  :destroy
	
	belongs_to:artist
	belongs_to:label
end

app/models/track.rb
class Track < ActiveRecord::Base
	belongs_to:release
	
	validate :must_have_valid_trailer
	def must_have_valid_trailer
		unless trailer.include?("<iframe")
			errors.add(:trailer, "Must include an iframe tag")
		end
	end
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	validates_uniqueness_of :email
end

app/models/user_artist.rb
class UserArtist < ActiveRecord::Base
	belongs_to:user
	belongs_to:artist
end

app/models/user_label.rb
class UserLabel < ActiveRecord::Base
	belongs_to:user
	belongs_to:label
end

app/controllers/labels_controller.rb
class LabelsController < ApplicationController
  before_action :set_label, only: [:show, :edit, :update, :destroy]
  before_filter :authorise, :except =>[:index]
  
  # GET /labels
  # GET /labels.json
  def index
    @labels = Label.all
  end

  # GET /labels/1
  # GET /labels/1.json
  def show
  end

  # GET /labels/new
  def new
    @label = Label.new
  end

  # GET /labels/1/edit
  def edit
  end

  # POST /labels
  # POST /labels.json
  def create
    @label = Label.new(label_params)

    respond_to do |format|
      if @label.save
        format.html { redirect_to @label, notice: 'Label was successfully created.' }
        format.json { render :show, status: :created, location: @label }
      else
        format.html { render :new }
        format.json { render json: @label.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /labels/1
  # PATCH/PUT /labels/1.json
  def update
    respond_to do |format|
      if @label.update(label_params)
        format.html { redirect_to @label, notice: 'Label was successfully updated.' }
        format.json { render :show, status: :ok, location: @label }
      else
        format.html { render :edit }
        format.json { render json: @label.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /labels/1
  # DELETE /labels/1.json
  def destroy
    @label.destroy
    respond_to do |format|
      format.html { redirect_to labels_url, notice: 'Label was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_label
      @label = Label.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def label_params
      params.require(:label).permit(:name, :location, :image, :owner)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
before_action :authorise
  def home
  end
  
  def profile
	
  end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :set_track, only: [:show, :edit, :update, :destroy]
  before_filter :authorise, :except =>[:index]
  
  # GET /tracks
  # GET /tracks.json
  def index
    @tracks = Track.all
  end

  # GET /tracks/1
  # GET /tracks/1.json
  def show
  end

  # GET /tracks/new
  def new
    @track = Track.new
  end

  # GET /tracks/1/edit
  def edit
  end

  # POST /tracks
  # POST /tracks.json
  def create
    @track = Track.new(track_params)

    respond_to do |format|
      if @track.save
        format.html { redirect_to @track, notice: 'Track was successfully created.' }
        format.json { render :show, status: :created, location: @track }
      else
        format.html { render :new }
        format.json { render json: @track.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tracks/1
  # PATCH/PUT /tracks/1.json
  def update
    respond_to do |format|
      if @track.update(track_params)
        format.html { redirect_to @track, notice: 'Track was successfully updated.' }
        format.json { render :show, status: :ok, location: @track }
      else
        format.html { render :edit }
        format.json { render json: @track.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tracks/1
  # DELETE /tracks/1.json
  def destroy
    @track.destroy
    respond_to do |format|
      format.html { redirect_to tracks_url, notice: 'Track was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_track
      @track = Track.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def track_params
      params.require(:track).permit(:name, :video, :release_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
		Usermailer.welcome(@user).deliver
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :dob, :sex, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def logged_in?
		if session[:user_id].nil?
			return
		else
			@current_user = User.find_by_id(session[:user_id])
		end
	end
	
	
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/labels_helper.rb
module LabelsHelper
end

app/helpers/releases_helper.rb
module ReleasesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/helpers/user_artists_helper.rb
module UserArtistsHelper
end

app/helpers/user_labels_helper.rb
module UserLabelsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MusicPage</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<nav class="navbar navbar-inverse navbar-fixed-top">
		<div class="container-fluid">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="http://localhost:3000">Music 247</a>
			</div>
			<div id="navbar" class="navbar-collapse collapse">
						<ul class="nav navbar-nav navbar-right">
						<li><%= link_to "Artists", artists_path%></li>
						<li><%= link_to "Labels", labels_path %></li>
						<li><%= link_to "Releases", releases_path%></li>
						<li><%= link_to "Tracks", tracks_path%></li>
						<%if !logged_in? %>
							<li><%= link_to "Sign In", login_path %></li>
					<% else %>
						<li><%= link_to "Profile", profile_path%></li>
						<li><%= link_to "Sign Out", logout_path %></li>
					<% end %>
					  </ul>
					  <form class="navbar-form navbar-right">
						<input type="text" class="form-control" placeholder="Search...">
					  </form>
			</div>
		</div>
		</nav>
		</br></br></br>	


	<%= yield %>
	
<footer class="footer navbar-fixed-bottom">
		<div class="footer">
			<p class="text-muted">
				<ul class="list-group">
					<li class="list-group-item">Stephen Murphy: Music 247</li>
				</ul>
			</p>
		</div>
	</footer>	
</body>
</html>

app/views/pages/home.html.erb
<h1>Welcome to the music page</h1>
<h2>Why don't you register below!</h2>

<%= link_to "Register", new_user_path %>

app/views/pages/profile.html.erb
<!DOCTYPE html>
<h2 class = "sub-header">Profile</h2>
<center><p>This is your own personal profile. Here you can manage the artists and labels 
that you follow. You can also update your profile.</p></center>

Name: <%= @current_user.name %>
 </br>
Age: <%= time_ago_in_words ( @current_user.dob )%>
</br>
 
Your Labels: <%%>

</br>
Your Artists:
